# Generated by Django 3.1.4 on 2020-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movetype', models.CharField(max_length=100)),
                ('movedate', models.CharField(max_length=100)),
                ('movefrom', models.CharField(max_length=100)),
                ('moveto', models.CharField(max_length=100)),
                ('waytorecieve', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=100)),
            ],
        ),
    ]
